spring.application.name=document-flow


server.port=8071


spring.datasource.url=jdbc:mysql://localhost:3306/document_flow_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=your_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


app.upload.dir=${user.home}/document-flow/uploads


logging.level.org.springframework.integration=INFO
logging.level.com.tural.documentflow=DEBUG